package com.manual.todolist.mapper;

import com.manual.todolist.model.LoginHistory;
import com.manual.todolist.model.LoginHistoryExample;
import com.manual.todolist.model.LoginHistoryKey;
import com.manual.todolist.model.LoginHistoryWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface LoginHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbg.generated
     */
    long countByExample(LoginHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbg.generated
     */
    int deleteByExample(LoginHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(LoginHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbg.generated
     */
    int insert(LoginHistoryWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbg.generated
     */
    int insertSelective(LoginHistoryWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbg.generated
     */
    List<LoginHistoryWithBLOBs> selectByExampleWithBLOBs(LoginHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbg.generated
     */
    List<LoginHistory> selectByExample(LoginHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbg.generated
     */
    LoginHistoryWithBLOBs selectByPrimaryKey(LoginHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LoginHistoryWithBLOBs row, @Param("example") LoginHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") LoginHistoryWithBLOBs row, @Param("example") LoginHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LoginHistory row, @Param("example") LoginHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LoginHistoryWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LoginHistoryWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LoginHistory row);
}