package com.manual.todolist.mapper;

import com.manual.todolist.model.RolesUsers;
import com.manual.todolist.model.RolesUsersExample;
import com.manual.todolist.model.RolesUsersKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RolesUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_users
     *
     * @mbg.generated
     */
    long countByExample(RolesUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_users
     *
     * @mbg.generated
     */
    int deleteByExample(RolesUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_users
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(RolesUsersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_users
     *
     * @mbg.generated
     */
    int insert(RolesUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_users
     *
     * @mbg.generated
     */
    int insertSelective(RolesUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_users
     *
     * @mbg.generated
     */
    List<RolesUsers> selectByExample(RolesUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_users
     *
     * @mbg.generated
     */
    RolesUsers selectByPrimaryKey(RolesUsersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_users
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RolesUsers record, @Param("example") RolesUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_users
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RolesUsers record, @Param("example") RolesUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RolesUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RolesUsers record);
}