package com.manual.todolist.mapper;

import com.manual.todolist.model.UsersSys;
import com.manual.todolist.model.UsersSysExample;
import com.manual.todolist.model.UsersSysKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UsersSysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_sys
     *
     * @mbg.generated
     */
    long countByExample(UsersSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_sys
     *
     * @mbg.generated
     */
    int deleteByExample(UsersSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_sys
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(UsersSysKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_sys
     *
     * @mbg.generated
     */
    int insert(UsersSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_sys
     *
     * @mbg.generated
     */
    int insertSelective(UsersSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_sys
     *
     * @mbg.generated
     */
    List<UsersSys> selectByExample(UsersSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_sys
     *
     * @mbg.generated
     */
    UsersSys selectByPrimaryKey(UsersSysKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_sys
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UsersSys record, @Param("example") UsersSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_sys
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UsersSys record, @Param("example") UsersSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_sys
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UsersSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_sys
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UsersSys record);
}