package com.manual.todolist.model;

import java.util.Date;

public class LoginHistoryKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_history.login_datetime
     *
     * @mbg.generated
     */
    private Date loginDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_history.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_history.login_datetime
     *
     * @return the value of login_history.login_datetime
     *
     * @mbg.generated
     */
    public Date getLoginDatetime() {
        return loginDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_history.login_datetime
     *
     * @param loginDatetime the value for login_history.login_datetime
     *
     * @mbg.generated
     */
    public void setLoginDatetime(Date loginDatetime) {
        this.loginDatetime = loginDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_history.username
     *
     * @return the value of login_history.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_history.username
     *
     * @param username the value for login_history.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }
}