package com.manual.todolist.model;

public class LoginHistoryWithBLOBs extends LoginHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_history.browser
     *
     * @mbg.generated
     */
    private String browser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_history.browser
     *
     * @return the value of login_history.browser
     *
     * @mbg.generated
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_history.browser
     *
     * @param browser the value for login_history.browser
     *
     * @mbg.generated
     */
    public void setBrowser(String browser) {
        this.browser = browser;
    }
}