package com.manual.todolist.model;

public class RolesUsers extends RolesUsersKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles_users.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles_users.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles_users.name
     *
     * @return the value of roles_users.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles_users.name
     *
     * @param name the value for roles_users.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles_users.email
     *
     * @return the value of roles_users.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles_users.email
     *
     * @param email the value for roles_users.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }
}