package com.manual.todolist.model;

public class RolesUsersKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles_users.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles_users.role
     *
     * @mbg.generated
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles_users.username
     *
     * @return the value of roles_users.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles_users.username
     *
     * @param username the value for roles_users.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles_users.role
     *
     * @return the value of roles_users.role
     *
     * @mbg.generated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles_users.role
     *
     * @param role the value for roles_users.role
     *
     * @mbg.generated
     */
    public void setRole(String role) {
        this.role = role;
    }
}