package com.manual.todolist.model;

import java.util.Date;

public class UsersSys extends UsersSysKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_sys.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_sys.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_sys.create_datetime
     *
     * @mbg.generated
     */
    private Date createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_sys.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_sys.create_by_module
     *
     * @mbg.generated
     */
    private String createByModule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_sys.update_datetime
     *
     * @mbg.generated
     */
    private Date updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_sys.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_sys.update_by_module
     *
     * @mbg.generated
     */
    private String updateByModule;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_sys.username
     *
     * @return the value of users_sys.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_sys.username
     *
     * @param username the value for users_sys.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_sys.password
     *
     * @return the value of users_sys.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_sys.password
     *
     * @param password the value for users_sys.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_sys.create_datetime
     *
     * @return the value of users_sys.create_datetime
     *
     * @mbg.generated
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_sys.create_datetime
     *
     * @param createDatetime the value for users_sys.create_datetime
     *
     * @mbg.generated
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_sys.create_by
     *
     * @return the value of users_sys.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_sys.create_by
     *
     * @param createBy the value for users_sys.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_sys.create_by_module
     *
     * @return the value of users_sys.create_by_module
     *
     * @mbg.generated
     */
    public String getCreateByModule() {
        return createByModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_sys.create_by_module
     *
     * @param createByModule the value for users_sys.create_by_module
     *
     * @mbg.generated
     */
    public void setCreateByModule(String createByModule) {
        this.createByModule = createByModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_sys.update_datetime
     *
     * @return the value of users_sys.update_datetime
     *
     * @mbg.generated
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_sys.update_datetime
     *
     * @param updateDatetime the value for users_sys.update_datetime
     *
     * @mbg.generated
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_sys.update_by
     *
     * @return the value of users_sys.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_sys.update_by
     *
     * @param updateBy the value for users_sys.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_sys.update_by_module
     *
     * @return the value of users_sys.update_by_module
     *
     * @mbg.generated
     */
    public String getUpdateByModule() {
        return updateByModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_sys.update_by_module
     *
     * @param updateByModule the value for users_sys.update_by_module
     *
     * @mbg.generated
     */
    public void setUpdateByModule(String updateByModule) {
        this.updateByModule = updateByModule;
    }
}