package com.manual.todolist.model;

public class UsersSysKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_sys.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_sys.id
     *
     * @return the value of users_sys.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_sys.id
     *
     * @param id the value for users_sys.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }
}