package com.manual.todolist.model;

public class UsersSys extends UsersSysKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_sys.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_sys.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_sys.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_sys.name
     *
     * @return the value of users_sys.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_sys.name
     *
     * @param name the value for users_sys.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_sys.email
     *
     * @return the value of users_sys.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_sys.email
     *
     * @param email the value for users_sys.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_sys.password
     *
     * @return the value of users_sys.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_sys.password
     *
     * @param password the value for users_sys.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }
}