package com.manual.todolist.model;

public class UsersSysKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_sys.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_sys.email
     *
     * @return the value of users_sys.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_sys.email
     *
     * @param email the value for users_sys.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }
}